/*
 * Created by IntelliJ IDEA.
 * User: calum
 * Date: 30-Aug-2002
 * Time: 14:15:55
 * To change template for new class use
 * Code Style | Class Templates options (Tools | IDE Options).
 */
package org.jini.projects.athena.service.ui;

/**
 *
 * @author  Internet
 */
public class TypesPanelArray extends javax.swing.JPanel {

    /** Creates new form TypesPanel */
    public TypesPanelArray() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        header = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        repeater = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        separator = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tails = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Header");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(jLabel1, gridBagConstraints);

        header.setBackground(new java.awt.Color(224, 224, 255));
        header.setEditable(false);
        header.setForeground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 12);
        gridBagConstraints.weightx = 1.0;
        add(header, gridBagConstraints);

        jLabel2.setText("Repeater");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(jLabel2, gridBagConstraints);

        repeater.setBackground(new java.awt.Color(224, 224, 255));
        repeater.setEditable(false);
        repeater.setForeground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 12);
        gridBagConstraints.weightx = 1.0;
        add(repeater, gridBagConstraints);

        jLabel3.setText("Separator");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(jLabel3, gridBagConstraints);

        separator.setBackground(new java.awt.Color(224, 224, 255));
        separator.setEditable(false);
        separator.setForeground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 12);
        gridBagConstraints.weightx = 1.0;
        add(separator, gridBagConstraints);

        jLabel4.setText("Tail");
        jLabel4.setToolTipText("null");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 6, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        add(jLabel4, gridBagConstraints);

        tails.setBackground(new java.awt.Color(224, 224, 255));
        tails.setEditable(false);
        tails.setForeground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 12);
        gridBagConstraints.weightx = 1.0;
        add(tails, gridBagConstraints);

    }


    // Variables declaration - do not modify
    private javax.swing.JTextField tails;
    private javax.swing.JTextField separator;
    private javax.swing.JTextField repeater;
    private javax.swing.JTextField header;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration

    public void setData(String head, String repeater, String separator, String tail) {
        this.header.setText(head);
        this.repeater.setText(repeater);
        this.separator.setText(separator);
        this.tails.setText(tail);
    }

    public void clear() {
        this.header.setText("");
        this.repeater.setText("");
        this.separator.setText("");
        this.tails.setText("");
    }
}
