/*
 * Created by IntelliJ IDEA.
 * User: calum
 * Date: 30-Aug-2002
 * Time: 14:16:17
 * To change template for new class use
 * Code Style | Class Templates options (Tools | IDE Options).
 */
package org.jini.projects.athena.service.ui;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.util.regex.Pattern;

import javax.swing.JLabel;

/**
 *
 * @author  Internet
 */
public class TypesPanelExpression extends javax.swing.JPanel {

    /** Creates new form TypesPanelExpression */
    public TypesPanelExpression() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new FlowLayout(FlowLayout.CENTER));

        jLabel1.setText("Expression");

        add(jLabel1);

        jTextField1.setBackground(new java.awt.Color(224, 224, 255));
        jTextField1.setText("Expression");
        jTextField1.setEditable(true);
        jTextField1.setMinimumSize(new Dimension(100, 24));
        jTextField1.setPreferredSize(new Dimension(100, 24));
        jTextField1.setSize(100, 24);
        add(jTextField1);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        JLabel testLabel = new JLabel("Test");

        jPanel1.setBorder(new javax.swing.border.TitledBorder("Test"));
        jLabel2.setText("Data");
        jLabel2.setToolTipText("null");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 6, 12);
        gridBagConstraints.gridx = 5;
        add(jLabel2);

        jTextField2.setText(" ");
        jTextField2.setMinimumSize(new Dimension(100, 24));
        jTextField2.setPreferredSize(new Dimension(100, 24));
        jTextField2.setSize(100, 24);
        add(jTextField2);

        jButton1.setMnemonic('T');
        jButton1.setText("Test");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jButton1.setMinimumSize(new Dimension(80, 24));
        jButton1.setPreferredSize(new Dimension(80, 24));
        jButton1.setSize(80, 24);
        add(jButton1);

        jLabel3.setForeground(java.awt.Color.green);
        jLabel3.setText("");
        jLabel3.setMinimumSize(new Dimension(80, 24));
        jLabel3.setPreferredSize(new Dimension(80, 24));
        jLabel3.setSize(80, 24);
        jLabel3.setToolTipText("null");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jLabel3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.gridwidth = 2;

        jLabel3.setHorizontalAlignment(JLabel.CENTER);

    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // Add your handling code here:
        if (Pattern.matches(jTextField1.getText(), jTextField2.getText())) {
            jLabel3.setForeground(new java.awt.Color(0, 128, 0));
            jLabel3.setText("SUCCESS!");
        } else {
            jLabel3.setForeground(new java.awt.Color(255, 0, 0));
            jLabel3.setText("Failure");
        }

    }


    // Variables declaration - do not modify
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jButton1;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration

}
