/*
 * Created by IntelliJ IDEA.
 * User: calum
 * Date: 30-Aug-2002
 * Time: 14:16:05
 * To change template for new class use
 * Code Style | Class Templates options (Tools | IDE Options).
 */
package org.jini.projects.athena.service.ui;

import javax.swing.DefaultListModel;

/**
 *
 * @author  Internet
 */
public class TypesPanelObject extends javax.swing.JPanel {

    /** Creates new form TypesPanelObject */
    public TypesPanelObject() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList(dlm);


        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Fields");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 12, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        add(jLabel1, gridBagConstraints);
        jList1.setBackground(new java.awt.Color(224, 224, 255));
        jScrollPane1.setViewportView(jList1);


        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 12);
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane1, gridBagConstraints);

    }


    // Variables declaration - do not modify
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList jList1;
    private javax.swing.JLabel jLabel1;
    public DefaultListModel dlm = new DefaultListModel();
    // End of variables declaration

    public void clear() {
        dlm.clear();
    }
}
